node {
    
    stage('GitCheckout'){
        checkout scm
    } 

  stage('Init Stage'){
        env.ACR_NAME = "testrigregistry"
        env.SUBSCRIPTION_ID = "57b13db8-88cf-4fe6-924b-ae10dc6fadee"
        env.AKS_NAME = "demo-aks"
        env.RESOURCE_GROUP = "demo-rg"
	    // env.BRANCH_NAME = env.BRANCH_NAME.replaceAll('/','_')
    }


    stage('Deploying'){
    withCredentials([azureServicePrincipal('test-rig-demo-jenkins')]) {
        sh '''
            COLOR=$(echo ${NAMESPACE} | cut -d "-" -f2)
            rm  ~/.kube/config
            az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET -t $AZURE_TENANT_ID
            az aks get-credentials --resource-group demo-rg --subscription 57b13db8-88cf-4fe6-924b-ae10dc6fadee   --name demo-aks
            echo NAMESPACE=${NAMESPACE}
            echo TAG_SPRFE=${SPRMONOLITH}
            echo COLOR is ${COLOR}
            helm list demo-${COLOR}
            if [ "$(helm list -q self-${COLOR})" != "" ]
            then 
                helm del --purge self-${COLOR}
            fi

            helm install --name self-${COLOR} --namespace self-${COLOR} helm/spr-monolith --set image.tag=${TAG_SPRMONOLITH}
        '''
    }} 
}
