node {
    
    stage('GitCheckout'){
        checkout scm
    } 

  stage('Init Stage'){
        env.ACR_NAME = "testrigregistry"
        env.SUBSCRIPTION_ID = "57b13db8-88cf-4fe6-924b-ae10dc6fadee"
        env.AKS_NAME = "demo-aks"
        env.RESOURCE_GROUP = "demo-rg"
	    // env.BRANCH_NAME = env.BRANCH_NAME.replaceAll('/','_')
    }


    stage('Deploying'){
    withCredentials([azureServicePrincipal('test-rig-demo-jenkins')]) {
        sh '''
            COLOR=$(echo ${NAMESPACE} | cut -d "-" -f2)
            az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET -t $AZURE_TENANT_ID
            echo NAMESPACE=${NAMESPACE}
            echo TAG_SPRFE=${TAG_SPRFE}
            echo TAG_SPRBE=${TAG_SPRBE}
            echo COLOR is ${COLOR}
            helm list demo-${COLOR}
            if [ "$(helm list -q demo-${COLOR})" != "" ]
            then 
                helm del --purge demo-${COLOR}
            fi

            kubectl delete job demo-${COLOR} --namespace=self-${COLOR} --ignore-not-found 
            sleep 5
            helm install --dep-up --name demo-${COLOR} --namespace self-${COLOR} --timeout 300  helm/demo --set sprbe.image.tag=${TAG_SPRBE},sprfe.image.tag=${TAG_SPRFE}
        '''
    }} 
    

}
